
package utility;

public class TestConfig{


	
	public static String server="smtp.gmail.com";
	public static String from = "anujray23@gmail.com";
	public static String password = "rwreuecuedexenmc"; // password generated by gmail security settings
	public static String[] to ={"23decanuj@gmail.com","parul.chitransh@gmail.com"};
	public static String subject = "Report 13-9-23 ";
	public static String messageBody ="title of report any TestMessage";
	public static String attachmentPath= System.getProperty("user.dir")+"\\src\\test\\java\\reports\\ResponsiveTestReport.html";
	public static String attachmentName="TestResults.html";
}
	
